server:
  port: 8080
  servlet:
    context-path: /share-app-api

spring:
  application:
    name: share-app-api
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #??

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.ssy.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

logging:
  config: classpath:log/logback-spring.xml

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.ssy.share.app.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true    #??????
    username: admin   #???
    password: 123456  #??


auth:
  valid_urls:
    - /auth/logout
    - /user/**
    - /resource/publish

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-nanjing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: kmSs
    # oss的存储空间
    bucketName: flo

share:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018e07b6f8892dc6
      accountToken: 9e43777038eb4001a25a416995eda92a
      appId: 2c94811c8cd4da0a018e07b6fa0a2dcd
      templateId: 1